metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - filesystem
    - fsstat
  enabled: true
  period: 10s

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - event
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "changeme"

setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"
setup.ilm.enabled: false 